### ISSUE TITLE
QT TeamTalk accessibility problems with JAWS

### ISSUE THREAD

**Issue by adns44** [BearWare/TeamTalk5#994]
Hi,

I experience some problems in QT client with JAWS.
My config: Windows 10 64 bit PRO 21H1, JAWS2021
- When I navigate with tabs, the channels tree not shown by tab, it talked only when I press up or down key.
- In chat history, if a message longer than a line on screen, JAWS reads entire message on a line, but the lines are same twice, if the message two lines long. Some events are repeated too, e.g. logged in or logged out of the server.
- In user list dialog (ctrl+shift+u) can't use CTRL+c to copy user info. Can't use local menu, when I press it, it opens the actual item's context menu on channel list. E.G. if I focus on my name on channels list, open users list, select my friend in another channel, press local menu, click to user info and enter, it gives my infos. When I press ESC, I moved back to the channels list, but the users list kept on screen. If I press CTRL+shift+u again, and ESC I can hide it.
- Please turn off VuMeter updates by default when screen reader on, very annoying to hear the percents.
- In channels list, when there are nested channels, and users in channel, I not see the level. E.G. there are two channel in the root, test1 and test5. If I expand test1, and there are 2 users, if there is a subchannel, I don't know its level. I don't know that test2 is in test1, or in the root, after test1.
- I can't use navigate on tabs in main Window and in preferences the home and end keys, these aren't moving to the first and last item.
- JAWS can't read the host address in server list if I navigate by characters. If I provide a new, if I mispelled, I must copy it, or delete the full line and retry to write it.
- When I'm deleting chars by backspace or del key in edit fields, I don't know what deleted or after the delete, JAWS always reads "empty".
- If I check the contents the edit field, e.g. new message in user or personal chat, by navigating left and right keys, I hear an empty char before the last. It seems that there is an empty char, but there isn't, only JAWS see it.
- When I press right arrow key on a channel where 0 users, and there hasn't any subchannels, or on an user in a channel, JAWS says "text message transmission allowed". I can go back with left arrow, but it drops me a level uper. E.G. if I did in a subchannel, drops me back to root. If it is a feature, where I can turn on or off audio, video for an user, implement the possibility to navigate back on the list, e.g. with left arrow.
- In stepping edit fields (e.g. channel bitrate or latency) I can't check the values with arrow keys, it says empty. When i change with up or down, it says empty too. I only can check with tab and shift+tab.

I have these experiences in the past days. I hoppe that I can improve the QT client accessibility with my feedbacks. I think this heading, make the QT client accessibility is very good, but there are bugs.

**Comment by Oreonan** [comment]
I made your requested change on default VU-Meter state in PR #995 (waiting for approval)
Unfortunately lot of issues you found are directly related to Qt, I reported some of them to Qt and now we are waiting for a correction.
Until Qt fixes the reported issues, this JAWS script from Doug Lee fixed some of them, can  you please test with this script?
https://dlee.org/teamtalk/qt/
You can say here what issues are still presents if you use this script.

**Comment by Oreonan** [comment]
I also fixed the home and end keys behavior in PR #997

**Comment by adns44** [comment]
Thanks for the fast reply and changes!
I installed the script.
- It solved the tree view tab navigation problem, but nesting level unknown too.
- Solved the message edit fields navigation and char deletion, but not solved the history field line repeating problem.

I experienced another problem, in file menu the exit command not ALT+f4, only F4 said.

I wait the QT dev team's solutions. I hoppe that they fix the accessibility problems because these are shown in VLC and other QT apps.

**Comment by Oreonan** [comment]
Yes, Qt adds an alt before all menu keys, I'll report also this issue.
I'll see with the developer of JAWS script if a solution can be find for the latest issues you have.
For now I suggest to let this issue open to list all issues and follow the corrections.

**Comment by dglee42** [comment]
My notes on all issues in this thread so far, as the JAWS script author:

Tab not saying TreeView: Fixed by scripts and verified in a comment here as fixed.

Tree level not speaking: Fixed by scripts and working here, but it sounds like the original issue creator here is not seeing that as fixed?

JAWS says full line for each physical (wrapped) line for a long message: Known and not fixed, not likely to be fixed by scripts, explanation after this issue list.

Events repeated on Up/Down arrows: Same as above, but maximize your TeamTalk window to reduce this problem significantly.

Ctrl+C and wrong context menu result from Online Users screen: Verified here and definitely an app issue not a script issue.

VU meter updates: The scripts disable the sounds for these but turning them off when the user asks for accessibility on installation is a very good idea.

Home/End not working on Tab controls: Sounds like that will be fixed in the app.

Can't arrow through edit combo values like Host in the F2 screen: Noted, I wrote it down as an issue to script if I can. And I think I can. Qt should still fix this though by doing these two things I think: (1) Make UIA report that focus is on the edit control rather than on its parent dropdown control, and (2) make the fix to the edit control issue of reporting the wrong character (or blank) during Left/Right arrows also apply to these edit controls.

Del in edit field, and last char in edit field wrong: See above; edit control issues for Qt to fix. I did fix them in JAWS scripts for now. I also fixed Backspace with scripts.

Right arrow on channel: Must be addressed in app.

Up/Down say Blank in spin controls: Noted for scripting. Workaround: Use SayLine (JAWSKey+Up) to check current value. Works with and without scripts.

Exit in File menu says F4 instead of Alt+F4: Verified here, to be fixed in app or Qt.

Details on the repeating history line and saying whole line issues (technical):

The problem is with the way the UIA Text pattern works for these edit controls. UIA says that a "line" consists of everything between two end-of-line characters. A long line can wrap into several lines on screen though, and there will be no division between these lines in UIA. This is why JAWS says the whole line for every wrap line in that logical line. Up and Down arrows move among physical lines though; so each time the cursor lands on a physical line, JAWS asks for that line and gets the whole thing.

I tried to find a way to split the lines up. I can count the physical lines by counting rectangles under a logical line, but I have not found a way to get the UIA text range for any specific physical rectangle.

I could alter what Up and Down arrows do, making them jump from one whole logical line to another; but I hesitate to do this for performance and other reasons. If Qt does not fix this issue somehow, I might eventually do that. Meanwhile, maximize the screen to reduce the line wrapping and thus make this issue happen less often.

**Comment by Oreonan** [comment]
Here are the advancements from my part
* I've fixed the "View user informations" context menu from online users dialog in commit e41adaf, this will be include in 5.8.1.
* I've changed the behavior of CTRL+C command from online users dialog in PR #998, when this PR will be merge, press CTRL+C on a user in this dialog will copy all user informations as presenting for screen readers.

**Comment by dglee42** [comment]
I posted an update to the JAWS scripts for TeamTalk Qt, with nine fixes, mostly for combo boxes, edit combos, and spin controls. Release notes (and docs and script download) at https://www.dlee.org/teamtalk/qt#hist

**Comment by adns44** [comment]
Thank you for your replies!

I experienced some problems too. Sorry for the lots of bug reports!:D

@dglee42 
I tried the script, it seems to be very good! But I have some problems.
JAWS script:
- When I am using it, I can't use ő in hungarian keyboard (this means on English [ next to enter key). It goes into command mode. I can write ő to the chat if I press the key two times fast.
- When I press more than one (2--3 times) the INS+up arrow in CTRL+u user list, the JAWS (2021) crashes.

@Oreonan 
QT TT:
- When I try to write @ (at) character (ALTGR+v in Hungarian keyboard layout) the user moving paste section appears, and an error because I didn't select user to move. So I can't write @ and other alttgr chars to the channel chat. In private messages window it works well.
- When TOLK enabled, to hear TT actions auto with JAWS, when an event occured, JAWS losts the focus on the website or in other apps. It seems to be the QT tt pulls the JAWS focus but I can't navigate in it if I don't navigate to window. I can solve it if I turn off tolk but it isn't a good solution. I didn't have this experience in classic client.

Thank you again for the bug fixes in the client and the JAWS script!

**Comment by dglee42** [comment]
To change the Command key, type it once and then JAWSKey+C or Insert+C and follow instructions. See https://www.dlee.org/code_common.htm#mkcs_change for details.

The crash in the Ctrl+Shift+U dialog on multiple quick Insert+Up commands is news to me, but I think I know why - an issue I have not reported yet because I was going to work around it myself: That and some other dialogs provide the entire row as the "name" of every column in the row. SayLine speaks the entire row one column at a time, so the whole row is repeated as many times as there are columns. JAWS can crash when too much text is sent at once for speaking; that has been true for years.

I have seen the focus loss but never realized it was related to Tolk being active. This is a weird one: Focus actually doesn't seem to change, but the keys for the current control won't work until I Tab and Shift+Tab to restore focus.

**Comment by Oreonan** [comment]
@adns44 I think the keyboard issue should be fixed directly in hungarian translation because it's related to this specific language.
Alternatively, we can maybe disable the associated actions when chat message input has focus.
Can you establish a list of shortcuts which cause problems?
I think that this specific issue will also have to be talk with @bear101

The focus issue is strange, I can't reproduce here... But, sometimes the focus is lock when you are on a channels tree item and the user change status for example, I'm trying to fix it but for now I have no really solution...

**Comment by bear101** [comment]
@Oreonan Is there something I should look into in the list of issues?

**Comment by Oreonan** [comment]
Yes, I copy here the two points I think you should look into:
- When I try to write @ (at) character (ALTGR+v in Hungarian keyboard layout) the user moving paste section appears, and an error because I didn't select user to move. So I can't write @ and other alttgr chars to the channel chat. In private messages window it works well.
- I experienced another problem, in file menu the exit command not ALT+f4, only F4 said.
Here are my comments for this:
* It's probably relative to hungarian translation, so I don't know what is the best, change ourself shortcuts for this language, wait for an hungarian translator, or disable some shortcuts when chat edit field has focus?
* In mainwindow.ui, line 1371, I can see alt+f4 define for shortcut to close client, is there really usefull? Alt+F4 is the standard shortcut to close an app.

**Comment by bear101** [comment]
@Oreonan ALTGR is the same as Ctrl+Alt, so I don't see how we should fix this.

Should we remove the Alt+F4 shortcut since it's default anyway? On macOS Cmd+Q is default for Quit anyway. I guess Alt+F4 will quit on Windows anyway?

**Comment by Oreonan** [comment]
Yes, it's why I think to a translation issue, shortcuts are translatables, so if CTRL+Alt+Something cause a problem, the shortcut should probably be change to another like CTRL+Alt+Shift+Something (or just replace the Something by another) to fix it.
Yes, I think we should remove Alt+F4 shortcut.

**Comment by bear101** [comment]
If I remember correctly the shortcuts can be changed in the translation file (.ts file). E.g. [here](https://github.com/BearWare/TeamTalk5/blob/master/Client/qtTeamTalk/languages/Danish.ts#L3770)

**Comment by bear101** [comment]
Then the Hungarian translation would have to translate Ctrl+Alt+V to another key mapping.

**Comment by Oreonan** [comment]
Yes, that's exactly what I wanted to say. My explanations could not be very clear :)

**Comment by bear101** [comment]
I'll leave it to the Hungarian translator to update the shortcut
